// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProClinic.Api.Data;

#nullable disable

namespace ProClinic.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108135532_AdicionarColunaMedicoSolicitante")]
    partial class AdicionarColunaMedicoSolicitante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProClinic.Api.Models.AgendaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int?>("EquipamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("HorarioFim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntervaloMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendaConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<string>("CpfPaciente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataLaudo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text");

                    b.Property<int?>("LoteTissId")
                        .HasColumnType("integer");

                    b.Property<int?>("MedicoLaudoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MedicoSolicitanteId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroCarteirinha")
                        .HasColumnType("text");

                    b.Property<string>("NumeroGuia")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("OrdemServico")
                        .HasColumnType("text");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<string>("SenhaAutorizacao")
                        .HasColumnType("text");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusLaudo")
                        .HasColumnType("text");

                    b.Property<string>("TextoLaudo")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AgendaConfigId");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("CpfPaciente");

                    b.HasIndex("LoteTissId");

                    b.HasIndex("MedicoLaudoId");

                    b.HasIndex("MedicoSolicitanteId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ProClinic.Api.Models.AgendamentoDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.ToTable("AgendamentoDespesas");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistroAns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorConsulta")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Convenios");
                });

            modelBuilder.Entity("ProClinic.Api.Models.ConvenioServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoNoConvenio")
                        .HasColumnType("text");

                    b.Property<int>("ConvenioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvenioId");

                    b.HasIndex("ServicoId");

                    b.ToTable("TabelaPrecos");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AETitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .HasColumnType("text");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Porta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("ProClinic.Api.Models.FraseLaudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MascaraLaudoId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MascaraLaudoId");

                    b.ToTable("FrasesLaudo");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GrupoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GruposUsuario");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GrupoUsuarioPermissao", b =>
                {
                    b.Property<int>("GruposId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissoesId")
                        .HasColumnType("integer");

                    b.HasKey("GruposId", "PermissoesId");

                    b.HasIndex("PermissoesId");

                    b.ToTable("GrupoUsuarioPermissao");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GuiaTiss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("AtendimentoRN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CBOSSolicitante")
                        .HasColumnType("text");

                    b.Property<string>("CaraterAtendimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConselhoProfissional")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataValidadeSenha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Gerada")
                        .HasColumnType("boolean");

                    b.Property<string>("HoraFinal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraInicial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndicacaoAcidente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LoteTissId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeProfissionalSolicitante")
                        .HasColumnType("text");

                    b.Property<string>("NumeroCarteira")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroConselhoSolicitante")
                        .HasColumnType("text");

                    b.Property<string>("NumeroGuiaOperadora")
                        .HasColumnType("text");

                    b.Property<string>("NumeroGuiaPrestador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegimeAtendimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistroAns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UFSolicitante")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.ToTable("GuiasTiss");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GuiaTissDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuiaTissId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuiaTissId");

                    b.ToTable("GuiasTissDespesas");
                });

            modelBuilder.Entity("ProClinic.Api.Models.LoteTiss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConvenioNome")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("QtdGuias")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("XmlConteudo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LotesTiss");
                });

            modelBuilder.Entity("ProClinic.Api.Models.MascaraLaudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Atalho")
                        .HasColumnType("text");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExameNome")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MascarasLaudo");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoTuss")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssinaturaBase64")
                        .HasColumnType("text");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EhCorpoClinico")
                        .HasColumnType("boolean");

                    b.Property<bool>("EhSolicitante")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Convenio")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoTuss")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNES")
                        .HasColumnType("text");

                    b.Property<string>("CNPJ")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Unidade");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("GrupoUsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrupoUsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProClinic.Api.Models.AgendaConfig", b =>
                {
                    b.HasOne("ProClinic.Api.Models.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId");

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Agendamento", b =>
                {
                    b.HasOne("ProClinic.Api.Models.AgendaConfig", "AgendaConfig")
                        .WithMany()
                        .HasForeignKey("AgendaConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProClinic.Api.Models.Convenio", "Convenio")
                        .WithMany()
                        .HasForeignKey("ConvenioId");

                    b.HasOne("ProClinic.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("CpfPaciente")
                        .HasPrincipalKey("CPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProClinic.Api.Models.LoteTiss", "LoteTiss")
                        .WithMany()
                        .HasForeignKey("LoteTissId");

                    b.HasOne("ProClinic.Api.Models.Medico", "MedicoLaudo")
                        .WithMany()
                        .HasForeignKey("MedicoLaudoId");

                    b.HasOne("ProClinic.Api.Models.Medico", "MedicoSolicitante")
                        .WithMany()
                        .HasForeignKey("MedicoSolicitanteId");

                    b.HasOne("ProClinic.Api.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId");

                    b.Navigation("AgendaConfig");

                    b.Navigation("Convenio");

                    b.Navigation("LoteTiss");

                    b.Navigation("MedicoLaudo");

                    b.Navigation("MedicoSolicitante");

                    b.Navigation("Paciente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("ProClinic.Api.Models.AgendamentoDespesa", b =>
                {
                    b.HasOne("ProClinic.Api.Models.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("ProClinic.Api.Models.ConvenioServico", b =>
                {
                    b.HasOne("ProClinic.Api.Models.Convenio", "Convenio")
                        .WithMany()
                        .HasForeignKey("ConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProClinic.Api.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("ProClinic.Api.Models.FraseLaudo", b =>
                {
                    b.HasOne("ProClinic.Api.Models.MascaraLaudo", "MascaraLaudo")
                        .WithMany()
                        .HasForeignKey("MascaraLaudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MascaraLaudo");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GrupoUsuarioPermissao", b =>
                {
                    b.HasOne("ProClinic.Api.Models.GrupoUsuario", "Grupo")
                        .WithMany()
                        .HasForeignKey("GruposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProClinic.Api.Models.Permissao", "Permissao")
                        .WithMany()
                        .HasForeignKey("PermissoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GuiaTiss", b =>
                {
                    b.HasOne("ProClinic.Api.Models.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GuiaTissDespesa", b =>
                {
                    b.HasOne("ProClinic.Api.Models.GuiaTiss", "GuiaTiss")
                        .WithMany("Despesas")
                        .HasForeignKey("GuiaTissId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuiaTiss");
                });

            modelBuilder.Entity("ProClinic.Api.Models.Usuario", b =>
                {
                    b.HasOne("ProClinic.Api.Models.GrupoUsuario", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ProClinic.Api.Models.GuiaTiss", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
